#include "../include/base_opencl.h"

char* read_kernel_source(const char* filename) {
    FILE* file = fopen(filename, "r");
    if (!file) {
        fprintf(stderr, "Error en OpenCL: No se encontro %s\n", filename);
        exit(1);
    }
    fseek(file, 0, SEEK_END);
    size_t size = ftell(file);
    rewind(file);
    
    char* source = (char*)malloc(size + 1);
    fread(source, 1, size, file);
    source[size] = '\0'; // EOF character
    fclose(file);
    return source;
}

opencl_env_t init_opencl_env(const char* kernel_path) {
    opencl_env_t env;
    cl_int err; // Saves the state codes generated by the OpenCL API
    cl_platform_id platform; // Represents the installed compute driver in Linux (e.g., Mesa / ROCm / oneAPI / etc.)

    // 1. Platform and Device scanning (Hardware Detection)
    // clGetPlatformIDs: GPU drivers are registered as "platforms". Get the first one available (assuming only one GPU).
    err = clGetPlatformIDs(1, &platform, NULL);
    if (err != CL_SUCCESS) {
        fprintf(stderr, "Error Crítico OpenCL: clGetPlatformIDs. Código %d\n", err);
        exit(1);
    }

    // clGetDeviceIDs: Looks inside the platform for a GPU device and saves its ID in env.device. (allows GPU-specific operations later)
    err = clGetDeviceIDs(platform, CL_DEVICE_TYPE_GPU, 1, &env.device, NULL);
    if (err != CL_SUCCESS) {
        fprintf(stderr, "Error Crítico OpenCL: clGetDeviceIDs. Código %d\n", err);
        exit(1);
    }

    // 2. Creates the OpenCL context and command queue for the selected GPU device.
    // clCreateContext: Isolates the GPU device in a "sandbox" where we can manage memory and execution without affecting the rest of the system.
    env.context = clCreateContext(NULL, 1, &env.device, NULL, NULL, &err);
    if (err != CL_SUCCESS) {
        fprintf(stderr, "Error Crítico OpenCL: clCreateContext. Código %d\n", err);
        exit(1);
    }
    // clCreateCommandQueueWithProperties: Opens a "communication channel" to the GPU, allowing us to send commands and data for processing.
    env.queue = clCreateCommandQueueWithProperties(env.context, env.device, 0, &err);
    if (err != CL_SUCCESS) {
        fprintf(stderr, "Error Crítico OpenCL: clCreateCommandQueueWithProperties. Código %d\n", err);
        exit(1);
    }

    // 3. JIT Compilation of the Kernel
    char* kernel_src = read_kernel_source(kernel_path);
    
    // clCreateProgramWithSource: Compiles the kernel source code at runtime. The driver translates the C-like kernel code into GPU machine code.
    env.program = clCreateProgramWithSource(env.context, 1, (const char**)&kernel_src, NULL, &err);
    free(kernel_src); // Free the source code string after creating the program object, as it's no longer needed in RAM.

    // clBuildProgram: The driver compiles the kernel source into executable code for the GPU. Also performs syntax checks and optimization.
    // If there are errors in the .cl file, this is where they will be caught.
    err = clBuildProgram(env.program, 1, &env.device, NULL, NULL, NULL);

    // STRICT DEBUGGING: if there are compilation errors, print the log.
    if (err != CL_SUCCESS) {
        size_t log_size;
        clGetProgramBuildInfo(env.program, env.device, CL_PROGRAM_BUILD_LOG, 0, NULL, &log_size);
        char* log = (char*)malloc(log_size);
        clGetProgramBuildInfo(env.program, env.device, CL_PROGRAM_BUILD_LOG, log_size, log, NULL);
        printf("Error crítico de compilación en %s:\n%s\n", kernel_path, log);
        exit(1);
    }

    // clCreateKernel: Extracts the compiled kernel function from the program object, making it ready for execution.
    // The string "search_pattern" must match the __kernel function name in kernel.cl.
    env.kernel = clCreateKernel(env.program, "search_pattern", &err);

    return env;
}

void search_patterns_opencl(opencl_env_t* env, const char* dna_string, int dna_string_length, pattern_t* patterns, int k_patterns) {
    cl_int err;

    /**  
    * * 1. Creation of GPU buffers (VRAM Allocation)
    * cl_mem: "GPU memory pointer".
    * clCreateBuffer: Reserve VRAM. 
    * CL_MEM_READ_ONLY: Optimizaton: Informs the driver that the GPU will only read from this buffer, allowing for better caching strategies.
    * CL_MEM_COPY_HOST_PTR: Copies the data from the host (RAM) to the device (VRAM) automatically.
    */

    cl_mem d_dna = clCreateBuffer(env->context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR, 
                                  dna_string_length * sizeof(char), (void*)dna_string, &err);
    
    cl_mem d_pattern = clCreateBuffer(env->context, CL_MEM_READ_ONLY, 
                                      patterns[0].length * sizeof(char), NULL, &err);
                                      
    // The GPU will write the results of the search (match positions) into this buffer. (CL_MEM_WRITE_ONLY)
    cl_mem d_results = clCreateBuffer(env->context, CL_MEM_WRITE_ONLY, 
                                         1000 * sizeof(int), NULL, &err);

    // Atomic counter. Needs to be readable and writable by the GPU to count matches. (CL_MEM_READ_WRITE)
    cl_mem d_counter = clCreateBuffer(env->context, CL_MEM_READ_WRITE, 
                                       sizeof(int), NULL, &err);

    // 2. Argument binding (Kernel Argument Setup)
    // clSetKernelArg: Works like a "pointer assignment" that tells the GPU which VRAM buffers
    // correspond to the __global variables in the kernel code. NOTE: indices must match the order of arguments in the __kernel function.
    clSetKernelArg(env->kernel, 0, sizeof(cl_mem), &d_dna);
    clSetKernelArg(env->kernel, 1, sizeof(cl_mem), &d_pattern);
    clSetKernelArg(env->kernel, 2, sizeof(cl_mem), &d_results);
    clSetKernelArg(env->kernel, 3, sizeof(cl_mem), &d_counter);
    clSetKernelArg(env->kernel, 5, sizeof(int), &dna_string_length);

    // 3. Execution loop for each pattern (Kernel Dispatch)
    for (int p = 0; p < k_patterns; p++) {
        // Our pattern implementation does not have a counter field, so we use an auxiliary variable to reset the GPU counter before each search.
        int zero = 0; 
        // clEnqueueWriteBuffer: Orders to the GPU to write the value of zero (0) into the d_counter buffer.
        // This resets the match count for each pattern.
        clEnqueueWriteBuffer(env->queue, d_counter, CL_TRUE, 0, sizeof(int), &zero, 0, NULL, NULL);

        // Copies the current pattern string into the d_pattern buffer in VRAM.
        clEnqueueWriteBuffer(env->queue, d_pattern, CL_TRUE, 0, patterns[p].length * sizeof(char), 
                             patterns[p].pattern, 0, NULL, NULL);

        // Update the kernel argument for the pattern length.
        clSetKernelArg(env->kernel, 4, sizeof(int), &patterns[p].length);

        // global_work_size: Defines the "grid" of parallel threads. We create 1 thread per nucleotide.
        size_t global_work_size = dna_string_length;

        // clEnqueueNDRangeKernel: Dispatches the asynchronous massive execution on the cores of the GPU.
        clEnqueueNDRangeKernel(env->queue, env->kernel, 1, NULL, &global_work_size, NULL, 0, NULL, NULL);

        // clEnqueueReadBuffer: Stops the CPU (CL_TRUE) until the GPU finishes, and extracts the counter value.
        int coincidences;
        clEnqueueReadBuffer(env->queue, d_counter, CL_TRUE, 0, sizeof(int), &coincidences, 0, NULL, NULL);

        // Results dumped by the GPU
        if (coincidences > 0) {
            int first_match;
            // Read the first match position from the d_results buffer, because we need only the first occurrence.
            clEnqueueReadBuffer(env->queue, d_results, CL_TRUE, 0, sizeof(int), &first_match, 0, NULL, NULL);
            patterns[p].state = MATCH;
            patterns[p].found_at = first_match; 
        } else {
            patterns[p].state = MISSING;
        }
    }

    // 4. Cleanup of GPU resources (VRAM Deallocation)
    // clReleaseMemObject: Frees the GPU video memory to avoid mem. leaks.
    clReleaseMemObject(d_dna);
    clReleaseMemObject(d_pattern);
    clReleaseMemObject(d_results);
    clReleaseMemObject(d_counter);
}

void finalize_opencl(opencl_env_t* env) {
    // clRelease*: Frees the '*' object created in the OpenCL environment to avoid memory leaks in the GPU driver.
    clReleaseKernel(env->kernel);
    clReleaseProgram(env->program);
    clReleaseCommandQueue(env->queue);
    clReleaseContext(env->context);
}

void run_opencl(params_t params) {
    int n = params.dna_length;
    int k_patterns = params.k_patterns;

    char *dna_string = vector_alloc(n);
    pattern_t *patterns = pattern_alloc(k_patterns, params.pattern_length);
    dna_generation(dna_string, n);
    pattern_generation(patterns, params.pattern_length, k_patterns);

    printf("Inicializando OpenCL y compilando kernel...\n");
    opencl_env_t ocl_env = init_opencl_env("src/kernel.cl");

    printf("Lanzando procesamiento en GPU...\n");
    search_patterns_opencl(&ocl_env, dna_string, n, patterns, k_patterns);

    int lim = (k_patterns < 5) ? k_patterns : 5;
    for(int i = 0; i < lim; i++) {
        printf("Patron %d [%s] - Estado: [%d] Pos: %d\n", 
                i, patterns[i].pattern, patterns[i].state, patterns[i].found_at);
    }

    finalize_opencl(&ocl_env);
    
    for (int i = 0; i < k_patterns; i++) free(patterns[i].pattern);
    free(patterns);
    free(dna_string);
}